name: Compile and Publish CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Manimehalan_CV.tex

      - name: Update Latest Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: 'Latest CV Build'
          body: 'Automated build of the latest CV from the main branch.'
          files: |
            cv.pdf